name: Dev - Deploy Backend

on:
  push:
    branches:
      - backend-dev
    paths:
      - 'apps/backend/**'
      - 'packages/database/**'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: shinabr2
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Build and Push Docker Image to Docker Hub
      - name: Build and Push Docker Image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          file: apps/backend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: shinabr2/sworld-backend:${{ github.ref_name }}-${{ github.sha::7 }}

      # Step 4: Deploy Docker Image to Google Cloud Run
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: 'sworld-backend'
          image: 'docker.io/shinabr2/sworld-backend:${{ github.ref_name }}-${{ github.sha::7 }}'
